dataset link:https://www.kaggle.com/datasets/shivamb/vehicle-claim-fraud-detection

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("fraud_oracle.csv")
df.head()

,Month,WeekOfMonth,DayOfWeek,Make,AccidentArea,DayOfWeekClaimed,MonthClaimed,WeekOfMonthClaimed,Sex,MaritalStatus,...,AgeOfVehicle,AgeOfPolicyHolder,PoliceReportFiled,WitnessPresent,AgentType,NumberOfSuppliments,AddressChange_Claim,NumberOfCars,Year,BasePolicy
0,Dec,5,Wednesday,Honda,Urban,Tuesday,Jan,1,Female,Single,...,3 years,26 to 30,No,No,External,none,1 year,3 to 4,1994,Liability
1,Jan,3,Wednesday,Honda,Urban,Monday,Jan,4,Male,Single,...,6 years,31 to 35,Yes,No,External,none,no change,1 vehicle,1994,Collision
2,Oct,5,Friday,Honda,Urban,Thursday,Nov,2,Male,Married,...,7 years,41 to 50,No,No,External,none,no change,1 vehicle,1994,Collision
3,Jun,2,Saturday,Toyota,Rural,Friday,Jul,1,Male,Married,...,more than 7,51 to 65,Yes,No,External,more than 5,no change,1 vehicle,1994,Liability
4,Jan,5,Monday,Honda,Urban,Tuesday,Feb,2,Female,Single,...,5 years,31 to 35,No,No,External,none,no change,1 vehicle,1994,Collision

In [3]:
df.isnull().sum()
df.dropna()

,Month,WeekOfMonth,DayOfWeek,Make,AccidentArea,DayOfWeekClaimed,MonthClaimed,WeekOfMonthClaimed,Sex,MaritalStatus,...,AgeOfVehicle,AgeOfPolicyHolder,PoliceReportFiled,WitnessPresent,AgentType,NumberOfSuppliments,AddressChange_Claim,NumberOfCars,Year,BasePolicy
0,Dec,5,Wednesday,Honda,Urban,Tuesday,Jan,1,Female,Single,...,3 years,26 to 30,No,No,External,none,1 year,3 to 4,1994,Liability
1,Jan,3,Wednesday,Honda,Urban,Monday,Jan,4,Male,Single,...,6 years,31 to 35,Yes,No,External,none,no change,1 vehicle,1994,Collision
2,Oct,5,Friday,Honda,Urban,Thursday,Nov,2,Male,Married,...,7 years,41 to 50,No,No,External,none,no change,1 vehicle,1994,Collision
3,Jun,2,Saturday,Toyota,Rural,Friday,Jul,1,Male,Married,...,more than 7,51 to 65,Yes,No,External,more than 5,no change,1 vehicle,1994,Liability
4,Jan,5,Monday,Honda,Urban,Tuesday,Feb,2,Female,Single,...,5 years,31 to 35,No,No,External,none,no change,1 vehicle,1994,Collision
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15415,Nov,4,Friday,Toyota,Urban,Tuesday,Nov,5,Male,Married,...,6 years,31 to 35,No,No,External,none,no change,1 vehicle,1996,Collision
15416,Nov,5,Thursday,Pontiac,Urban,Friday,Dec,1,Male,Married,...,6 years,31 to 35,No,No,External,more than 5,no change,3 to 4,1996,Liability
15417,Nov,5,Thursday,Toyota,Rural,Friday,Dec,1,Male,Single,...,5 years,26 to 30,No,No,External,1 to 2,no change,1 vehicle,1996,Collision
15418,Dec,1,Monday,Toyota,Urban,Thursday,Dec,2,Female,Married,...,2 years,31 to 35,No,No,External,more than 5,no change,1 vehicle,1996,All Perils
15419,Dec,2,Wednesday,Toyota,Urban,Thursday,Dec,3,Male,Single,...,5 years,26 to 30,No,No,External,1 to 2,no change,1 vehicle,1996,Collision

In [4]:
df.columns

Index(['Month', 'WeekOfMonth', 'DayOfWeek', 'Make', 'AccidentArea',
       'DayOfWeekClaimed', 'MonthClaimed', 'WeekOfMonthClaimed', 'Sex',
       'MaritalStatus', 'Age', 'Fault', 'PolicyType', 'VehicleCategory',
       'VehiclePrice', 'FraudFound_P', 'PolicyNumber', 'RepNumber',
       'Deductible', 'DriverRating', 'Days_Policy_Accident',
       'Days_Policy_Claim', 'PastNumberOfClaims', 'AgeOfVehicle',
       'AgeOfPolicyHolder', 'PoliceReportFiled', 'WitnessPresent', 'AgentType',
       'NumberOfSuppliments', 'AddressChange_Claim', 'NumberOfCars', 'Year',
       'BasePolicy'],
      dtype='object')

In [5]:
#check datset nature
df['FraudFound_P'] = (df['FraudFound_P']>0).astype(int)
print(f"Not Fraud:{sum(df['FraudFound_P']==0)}")
print(f"Fraud:{sum(df['FraudFound_P']==1)}")

Not Fraud:14497
Fraud:923

In [6]:
print("Data set is inbalanced")

Data set is inbalanced

In [7]:
X =df.drop('FraudFound_P',axis=1)
y=df['FraudFound_P']

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)

In [9]:
print(f"Shape of X_train before encoding: {X_train.shape}")

Shape of X_train before encoding: (12336, 32)

In [10]:
categorical_cols = X_train.select_dtypes(include='object').columns
print(f"Categorical columns to encode: {list(categorical_cols)}")

X_train_encoded = pd.get_dummies(X_train, columns=categorical_cols, drop_first=True)
X_test_encoded = pd.get_dummies(X_test, columns=categorical_cols, drop_first=True)

Categorical columns to encode: ['Month', 'DayOfWeek', 'Make', 'AccidentArea', 'DayOfWeekClaimed', 'MonthClaimed', 'Sex', 'MaritalStatus', 'Fault', 'PolicyType', 'VehicleCategory', 'VehiclePrice', 'Days_Policy_Accident', 'Days_Policy_Claim', 'PastNumberOfClaims', 'AgeOfVehicle', 'AgeOfPolicyHolder', 'PoliceReportFiled', 'WitnessPresent', 'AgentType', 'NumberOfSuppliments', 'AddressChange_Claim', 'NumberOfCars', 'BasePolicy']

In [11]:
print(f"Shape of X_train after encoding: {X_train_encoded.shape}")
print(f"Shape of X_test after encoding: {X_test_encoded.shape}")

Shape of X_train after encoding: (12336, 124)
Shape of X_test after encoding: (3084, 116)

In [12]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X_train_encoded, y_train)

print("Before:", y_train.value_counts())
print("After:", y_res.value_counts())

Before: FraudFound_P
0    11598
1      738
Name: count, dtype: int64
After: FraudFound_P
0    11598
1    11598
Name: count, dtype: int64

In [13]:
#stanndard scaler
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

X_res_scaled_smote=scaler.fit_transform(X_res)
X_test_scaled=scaler.transform(X_test_encoded)

ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- AddressChange_Claim_under 6 months
- DayOfWeekClaimed_Friday
- Days_Policy_Claim_none
- Make_Ferrari
- Make_Lexus
- ...

Random Forest

In [ ]:
#model training
from sklearn.ensemble import RandomForestClassifier
rf_model=RandomForestClassifier(max_depth=5,
                               random_state=42)
#model fixing
rf_model.fit(x_res_scaled_smote, y_res_smote)
#model prediction
rf_pred=rf_model.predict(x_test_scaled)
# evaluation
from sklearn.metrics import accuracy_score
rf_acc=accuracy_score(y_test, rf_pred)
rf_acc

Decision Tree

In [ ]:
#model training
from sklearn.tree import DecisionTreeClassifier
dt_model=DecisionTreeClassifier(max_depth=3,
                               random_state=42)
#model fixing
dt_model.fit(X_res_scaled_smote, y_res_smote)
#model prediction
dt_pred=rf_model.predict(X_test_scaled)
# evaluation
from sklearn.metrics import accuracy_score
dt_acc=accuracy_score(y_test, dt_pred)
dt_acc

SVM

In [ ]:
#model training
from sklearn.svm import SVC
svm_model=SVC(kernel='rbf',
             C=1,
             random_state=45)
#model fixing
svm_model.fit(X_res_scaled_smote, y_res_smote)
#model prediction
svm_pred=rf_model.predict(X_test_scaled)
# evaluation
from sklearn.metrics import accuracy_score
svm_acc=accuracy_score(y_test, svm_pred)
svm_acc

In [ ]:
model_accuracies={
    "DT":dt_acc,
    "RF":rf_acc,
    "SVM":svm_acc
}
model_accuracies

In [ ]:
best_model_name=max(model_accuracies,
                    key=model_accuracies.get)
best_accuracy=model_accuracies[best_model_name]
print(f"\n Best Model: {best_model_name}with accuracy of {best_accuracy:4f}")